name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu:20.04]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Install sudo
        run: |
          apt-get update
          apt-get install -y sudo
      - name: Script
        run: source install.bash
