name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Script
        run: source install.bash
