name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Script
        run: source install.bash
